### DISCUSSION TITLE
Deprecation notice - blueprint "host" and "execution_host"

### DISCUSSION THREAD

**Discussion by shirabendor-quali** [QualiTorque/qualitorque.github.io#227] [Announcements]
We are aligning all our terminology both in the UI and the blueprint to refer to "agent" instead of "execution_host" or "host".
The change in the blueprint is as follows:

```yaml
agent: # previously : "host"
  name: eks-ohio  

inputs:
  my_agent:
    type: agent # previously "execution_host"
```

The old syntax will continue to be supported for 3 months (i,e. until April 22, 2023).
