### DISCUSSION TITLE
Schedule pods on specific nodes using nodeSelector

### DISCUSSION THREAD

**Discussion by Shnitselon** [QualiTorque/qualitorque.github.io#271] [Announcements]
Torque now supports **nodeSelector** in Kubernetes environments, allowing users to assign pods to nodes based on their labels. This feature enables users to optimize resource usage and improve the performance of workloads running on Kubernetes clusters.

This is done by specifying (in the blueprint YAML's grain) the label(s) defined on the nodes.
For example: 
```
grains:
  nginx:
    kind: helm
    spec:
      source:
        store: spec2_repo_blue
        path: helm/nginx
      host:
        name: '{{ .inputs.host_name }}'
        kubernetes:
          nodeSelector:
          - app: torque
```

For details, see the Blueprint YAML article's [agent](https://docs.qtorque.io/blueprint-designer-guide/blueprints#agent) section.
