### DISCUSSION TITLE
Use of tfvars files in Terraform Grain

### DISCUSSION THREAD

**Discussion by shirabendor-quali** [QualiTorque/qualitorque.github.io#301] [Announcements]
You can now specify tfvars file in the terraform grain for Torque to automatically pick the variables and values.

Here is the syntax:

``` yaml
grains:
  database:
    kind: terraform
    spec:
      source:
        store: infra 
        path: terraform/rds
      authentication:
        - ...        
      ...
      inputs:
        ...
      tfvars-files:
      - source:
          store: <> 
          path: <>
      - source:
          store: <>
          path: <>
```

For more information: https://docs.qtorque.io/blueprint-designer-guide/blueprints/terraform-grain#tfvars-files-as-inputs-to-terraform-grain
