### DISCUSSION TITLE
Torque Deployment error

### DISCUSSION THREAD

**Discussion by kesavan-m-weblinktechs** [QualiTorque/qualitorque.github.io#311] [Q&A]
Hi, I'm having an issue with my torque deployment.

[](https://portal.qtorque.io/ss-aws-qa-ap-south-1/sandboxes/MFDlUbP9W5Np/devops/logs/docker-secret)

I checked the logs
```
Failed to establish the connection to the agent.
This might be a result of resource limitations or other issues in your cluster. Please check the cluster to understand the issue.
```

![image](https://github.com/QualiTorque/qualitorque.github.io/assets/104507671/3be6a825-dc40-4a64-ae57-933316021496)

then I check my cluster, I saw this error,
```
Failed to create kubernetes resource. {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"persistentvolumeclaims is forbidden: User \"system:serviceaccount:torque-agent-ss-aws-qa-ap-south-1-wxtybp9k6:torque-agent-sa-be8c59\" cannot create resource \"persistentvolumeclaims\" in API group \"\" in the namespace \"aws-6396d802-30\"","reason":"Forbidden","details":{"kind":"persistentvolumeclaims"},"code":403}
```

For this I update my

so I update my role 
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 namespace: {{ .Values.namespace }}
 name: {{ .Values.service_account }}-role
rules:
- apiGroups: [""]
  resources: ["secrets,persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  ```

After that also I got same error.

Please help me on this asap.
