### DISCUSSION TITLE
Quick Access Parameters

### DISCUSSION THREAD

**Discussion by mmackay21724** [QualiTorque/qualitorque.github.io#335] [Ideas]
Feature Request:: (unless it's already there) - **Non Critical**
In Quick access the parameter provided is labeled based on the variable name.
e.g.

```
vpn_address
reservation.com:20371    
```
Would be good to have a label instead.
e.g.

```
outputs: 
  fmc_server:
    value: '{{ .grains.sbx_creds.outputs.password }}'
    label: 'FMC Server'
    
```
